# Why NumPy?

In [1]:
import numpy as np

### Ndarrays

### 1-D Arrays

In [21]:
array_a = np.array([1,2,3])
print(array_a)
print(type(array_a))
print(array_a.shape)
ac = array_a.transpose
print(ac)
# This is a one dimensional array.
# This can be taken as representation of line in space.
# Shape is of one dimension with 3 elements, thus it shows a single value and the no. of elements as the value.

[1 2 3]
<class 'numpy.ndarray'>
(3,)
<built-in method transpose of numpy.ndarray object at 0x000002ADADCCE9F0>


### 2-D Arrays

In [36]:
array_b = np.array([[1,2,3],[4,5,6]])
print(array_b)
print(type(array_b))
print(array_b.shape)
print(array_b.size)
# This is a two dimensional array of 2 rows and 3 collumns or 2 rows 3 elements each.
# This one can be taken as a representation of plane in space.
# Shape is of 2 dimensions, 1st one representing the number of rows and the 2nd one representing the number of 
# columns.
# We can also access only the no. of rows and columns through indexing the arrays.

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6


### Scalars

In [23]:
array_c = np.array(12)
print(array_c)
print(array_c.shape)
print(type(array_c))
# This is a 0-D array of no rows and no columns.
# This is one representation of a single point in the space.
# If we put the point as follows it will represent a point of line or a point of space.
array_c_1 = np.array([12])
print(array_c_1.shape)
array_c_2 = np.array([[12]])
print(array_c_2.shape)

12
()
<class 'numpy.ndarray'>
(1,)
(1, 1)


### List vs Array

In [25]:
list_a = list([1,2,3,4,5,6])
list_b = list([[1,2,3],[4,5,6]])

In [28]:
# Lists are always an inclusion of sublists, so the len function shows the no. of inner sublists that is 2.
# To obtain the no. of elements in a sublist use indexing.
print(len(list_a))
print(len(list_b))
print(len(list_b[0]))

6
2
3


In [29]:
# Lists are only able to use the len function and can't use the shape function.
list_a.shape

AttributeError: 'list' object has no attribute 'shape'

In [33]:
list_c = list_b[0]+list_b[1] # The basic mathematical operations in lists dont occur element wise.
print(list_c) # Thus list c is a concatination rather than an element wise operation.

[1, 2, 3, 4, 5, 6]


In [35]:
array_d = array_b[0]+array_b[1]
print(array_d) # The operations in arrays are always element wise and thus we can use the built in functions well 
# on the arrays to do the calculation.

[5 7 9]
