# Working with Arrays

In [1]:
import numpy as np

## Slicing
- Slicing can also be known as interval indexing, while the simple indexing which we did before is known as fixed or specific indexing.
- Slicing basically refers to smaller arrays from the main arrays and may change a bit in dimensions.
- It can contain entire rows and columns of the original arrays, or just part of them.
- Creating a new array by taking chunks of values out of an existing one.
- The slices consist of adjacent piece of data.

In [2]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing
- We use : symbol for slicing, which expresses an interval of values.

In [4]:
# Here we refer to all the rows of matrix, cause we are not specifying any limit.
# Here we start slicing beginning before the colon, and ending one just before the number after the colon.
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Here we refer to the array after 0th index and end before 0th index, thus there are no rows before the first row and 
#itself.
matrix_A[0:0]

array([], shape=(0, 3), dtype=int32)

In [8]:
# Comma separates the 2 dimensions on which the slicing is done.
matrix_A[:,:] #We get all the rows and all columns, this is similar to A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# If we try to get something out of bounds we get a 0d array rather than an error.
matrix_A[2:,:]

array([], shape=(0, 3), dtype=int32)

In [11]:
matrix_A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
matrix_A[2:] # Remember A[n:] and A[:n] are complementary matrices.

array([], shape=(0, 3), dtype=int32)

In [16]:
matrix_A[:2,1:] # This will give us a 2D slice when we use the interval symbol.

array([[2, 3],
       [5, 6]])

In [21]:
matrix_A[:1] # This is called as a 2D slice.

array([[1, 2, 3]])

In [22]:
matrix_A[1] # This is called as a 1D slice.

array([4, 5, 6])

### Stepwise Slicing
- Stepwise slicing is similar to interval slicing, just the point is we specify a step size and that is used for the indexing or basically consider it as a jump.
- A[start:end:step,start:end:step] is the general format for step slicing.

In [26]:
matrix_b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# Stepping through every 2nd row in the mattrix.
matrix_b[::2,::]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [29]:
# Stepping through every 2nd column of the matrix.
matrix_b[::,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [33]:
# We can do the similar stepping with -ve steps, just keep in mind that for -ve steps the start is by default -1
# Unless specified other wise.
matrix_b[::-2,-3::-1]
#Here we first start from the last rows and move from the end of matrix that too from 3rd last column and then 
#moves element wise to the left with step size as 1

array([[10,  9],
       [ 2,  1]])

In [34]:
matrix_b[-1::-1,::2]

array([[ 9, 11],
       [ 5,  7],
       [ 1,  3]])

### Conditional Slicing
- In Conditional slicing we actually use the conditions to slice the data, we are actually making the use of the facility that every operation in the array is being done element wise and nothing else.
- One important bit that has to be kept in mind while working on the conditional slicing, is numpy actually flattens the array out first and then applies the condition and thus the final output which we obtain is always gonna be a one dimensional array. However rememeber the final elements will be in the same order as they are in the original array.

In [50]:
array = np.array([[1,2,3,4],[5,6,2,1],[0,3,1,0]])
array

array([[1, 2, 3, 4],
       [0, 1, 8, 9],
       [4, 6, 2, 8]])

In [55]:
array[:,:]>5 # We are basically filtering the whole array and get true only at those places where the value in 
#the matrix is >5

array([[False, False, False, False],
       [False, False,  True,  True],
       [False,  True, False,  True]])

In [56]:
# If we simply put the condition inside the index symbol we will get the elements which are set to true during the 
# condition.
array[array[:,:]>5]

array([8, 9, 6, 8])

In [57]:
array[array[:,:] == 5]

array([], dtype=int32)

In [58]:
array[array[:,:] <= 5]

array([1, 2, 3, 4, 0, 1, 4, 2])

In [59]:
array[(array[:,:] >= 1) &(array[:,:] <= 3)]

array([1, 2, 3, 1, 2])

## Dimensions and the Squeeze Function
- The squeeze function is pretty helpful, when we work with a matrix and need to reduce its dimensions and be consistent with the reduced dimensions output.

In [35]:
matrix_D = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [36]:
# Basically we are accessing a singular element with specific indexing.
type(matrix_D[0,0])

numpy.int32

In [37]:
print(matrix_D[0,0])

1


In [40]:
# Here we are accessing a singular element but we are using interval indexing in 
# one of the dimensions i.e. columns here and thus the output is also a 1-D array with 1 element
type(matrix_D[0,0:1])

numpy.ndarray

In [41]:
print(matrix_D[0,0:1])

[1]


In [42]:
type(matrix_D[0:1,0:1])

numpy.ndarray

In [45]:
# Now here we get a singular element in a 2D matrix cause we used 2 
# interval accessing.
print(matrix_D[0:1,0:1])

[[1]]


In [46]:
print(matrix_D[0,0].shape) # A Scalar
print(matrix_D[0,0:1].shape) # A vector or 1D array
print(matrix_D[0:1,0:1].shape)# A 2D array or a matrix.

()
(1,)
(1, 1)


In [47]:
# Basically we would like to be consistent with the dimensions of the
# array when we convert it from high type to the lower one.
# Thus we use the squeeze function, the squeeze function, actually to 
# reduce the dimensions of the data to the least dimensions.
# In all the above cases we will get a scalar value, rather than any other higher dimensions.

In [48]:
# All are Scalars
print(matrix_D[0,0].squeeze().shape) 
print(matrix_D[0,0:1].squeeze().shape) 
print(matrix_D[0:1,0:1].squeeze().shape)

()
()
()


In [49]:
# All are Scalars in terms of their output too.
# This will maintain consistency when slicing the output to 
# the smallest amount of data.
print(matrix_D[0,0].squeeze()) 
print(matrix_D[0,0:1].squeeze()) 
print(matrix_D[0:1,0:1].squeeze())

1
1
1
