### All the tasks that need to be done by a data analyst in preprocessing the data.
- 1) The analyst is provided with the necessary changes required in the dataset and also the dataset.
- In this preprocessing following bits need to be done:
    + Convert the data in the quantified form i.e. every value is numeric, for this we make categories and assign numbers or have positive, negative connotations or simple 0 and 1 as the values.
    + There is a need to convert USD values to EUR currency.
    + The data has to be clean and not possessing outliers and missing values for the model to run.
    + Filling values is done keeping in mind we are creating a CRM: Credit risk model for a bank so that we can find the defaulters on their details and not provide give them loans.
    + Thus the values are filled keeping in mind the creditworthiness of a customer.
        1) We need to be extreme risk-averse and distrustful.
        2) Missing information suggests foul play.
        3) If the information isn't available, we'll just assume the worst.
- 2) Its always a good idea to have the alterations done on paper before being done on data, this will save a lot of time in the long run.
- 3) The following tasks are performed on the data on a brief:
    + Importing and Examining Data.
    + Splitting the data to strings and numeric values and headers. This allows easy handling of the data.
    + Manipulating the data, by removing missing values, converting the strings to the equivalent numeric values on the base of the above instructions.
    + Creating checkpoints in the midway when major tasks like manipulating strings is done, then numeric cols is done etc.
    + Finally we may sort the dataset and combine all the splitted data into a single variable, ready to be imported into the data file.

### Functions used in the process and the use of the functions.
- np.loadtxt(),np.genfromtxt()
    + To know whether file has nan values or not and also importing the data.
- np.isnan()
    + To know whether there are nan_values in data or not with sum attribute.
- np.unique()
    + Pretty handy to know unique values in data, also their count and the index at which they appeared first.
    + Able to help in analytics like assigning mean or min or max or mode is useful for an array.
- np.isin()
    + Checks if certain value lies in a certain array.
- np.nanmean(),np.nanmin(),np.nanmax()
    + Gives the basic stats values.
- np.argwhere()
    + Gives the indices of elements satisfying a given condition.
- np.argsort()
    + Gives the indices where the element will belong after sorting array.
- np.where()
    + Helps to replace the values which are equal to certain specific values in a column.
- np.savez()
    + This will save the data in a np's archive format in which .npy files are stored which can be accessed faster.
- np.savetxt()
    + Helps to save the file in a csv format or txt format with a given fmt and delimiters.
- ndarray.chararray.strip()
    + Used to strip the strings from a common unnecessary part.
- np.reshape()
    + Used to reshape arrays so they are suitable for stacking or concatenating.
- np.vstack()
    + Used to stack vertically on top of each other.
- np.hstack()
    + Used to stack the arrays horizontally side by side.
- np.concatenate()
    + Used to concatenate the strings side by side.
- np.array_equal()
    + Used as validity testing whether 2 arrays are equal or not without comparing each entry by viewing by self or without looping.

## Importing the Packages

In [252]:
import numpy as np

In [253]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)
# Supress means supressing the scientific notation.
# Linewidth refers to the no. of characters to be seen in one line.
# Precision refers to the precision of the float numbers.

## Importing the Data

In [254]:
#raw_data_np = np.loadtxt('./Data/loan-data.csv',delimiter = ',') This doesn't work so we have missing values.
raw_data_np = np.genfromtxt('./Data/loan-data.csv',delimiter = ';',autostrip = True)
raw_data_np
# Looking at dataset we are not sure whether NaN values 

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data
- Here we see the no. of missing values. 
- Further to fill it we try to create means with raw data to prevent outlier making.
- We also get min and max arrays for every columns just in case to replace the missing values.

In [255]:
print(np.isnan(raw_data_np).sum()) #So many missing values.

88019


In [256]:
temporary_fill = np.nanmax(raw_data_np)+1
temporary_mean = np.nanmean(raw_data_np,axis = 0) #We are finding mean for every single column.

<ipython-input-256-dcbfdd4b8503>:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np,axis = 0) #We are finding mean for every single column.


In [257]:
# Observing the mean data.
temporary_mean 
# With this all the columns where mean is nan are the columns filled with strings only.

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [258]:
# Filling all the min, max and mean in an array.
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                          temporary_mean,
                          np.nanmax(raw_data_np, axis = 0)]) 
temporary_stats # Each 2d array is in same order as specified, above so mean comes in between.

<ipython-input-258-434f321d2c98>:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
<ipython-input-258-434f321d2c98>:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset
- We usually split the numeric and string columns to separate arrays so that we can work on them easily.
- Likewise we keep the data and the headers separate so that we can work on data more efficiently and when the work is done simply we will stack the data as we need.

### Splitting the Columns

In [259]:
#### Knowing the columns where the columns are strings.
string_columns = np.argwhere(np.isnan(temporary_mean)).squeeze(axis = 1)
numeric_columns = np.argwhere(np.isnan(temporary_mean)!=True).squeeze(axis = 1)
print(numeric_columns)
print(string_columns)

[ 0  2  4  6  7 13]
[ 1  3  5  8  9 10 11 12]


### Re-importing the Dataset

In [260]:
# Storing the particular columns in different arrays using genfromtxt, cause we can alter a dtype there easily.
strings_loan_data = np.genfromtxt('./Data/loan-data.csv',
                                  delimiter = ';',
                                  dtype = str,
                                  skip_header = 1,
                                  usecols = string_columns,
                                  autostrip = True) #Autostrip is very useful, while manipulating strings it becomes easy
# as the whitespaces are stripped.
strings_loan_data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [261]:
# Loading the numeric data and also filling the missing values.
numeric_loan_data = np.genfromtxt('./Data/loan-data.csv',
                                  delimiter = ';',
                                  usecols = numeric_columns,
                                  skip_header = 1,
                                  filling_values=temporary_fill)
numeric_loan_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [262]:
full_header = np.genfromtxt('./Data/loan-data.csv',
                                  delimiter = ';',
                                  skip_footer = raw_data_np.shape[0]-1,
                                  filling_values=temporary_fill, 
                            dtype = str,
                            autostrip= True)
full_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [263]:
strings_header = full_header[string_columns]
numeric_header = full_header[numeric_columns]

strings_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [264]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints
- Creating a function that will help create the checkpoints of data so that we don't loose out on the processing that has happened until a certain point.
- See how the function is structured, we are asking minimal bits as parameters, and the asking is intuitive and as per the needs of the savez function.

In [265]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [266]:
checkpoint_test_strings = checkpoint('checkpoint-test-strings',strings_header,strings_loan_data)

In [267]:
checkpoint_test_strings['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [268]:
checkpoint_test_strings['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [269]:
checkpoint_test_numeric = checkpoint('checkpoint-test-numeric',numeric_header,numeric_loan_data)
checkpoint_test_numeric['header']
checkpoint_test_numeric['data']

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

## Manipulating String Columns
- Here we start to work only with the strings collumns at first.
- Always have a preplan which column needs what alteration and then work on the columns one by one i.e. pretty efficient, needs less thought and is great.
- We are using np.unique() for knowing which values are present in the whole column, without having to look at each entry.
- Also while working we remove NaN values as per the instructions given by the team.
- Remember ask the specific needs to the team to give the best output.

In [270]:
strings_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [271]:
strings_header[0] = 'issue_date'

In [272]:
strings_loan_data = checkpoint_test_strings['data']

In [273]:
strings_loan_data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date
- We will convert the Months to numeric months so that handling of the months becomes a bit easy. 

In [274]:
np.unique(strings_loan_data[:,0]) # Unique does sort the data but its alphabetically being strings.

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [275]:
strings_loan_data[:,0] = np.chararray.strip(strings_loan_data[:,0],chars = '-15') # 

In [276]:
strings_loan_data[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [277]:
np.unique(strings_loan_data[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [278]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [279]:
# Doing this to assign the numeric values instead of strings, but they stay in form of strings.
for i in range(13):
        strings_loan_data[:,0] = np.where(strings_loan_data[:,0] == months[i],
                                          i,
                                          strings_loan_data[:,0])

In [280]:
np.unique(strings_loan_data[:,0]) # Strings are sorted by their ASCII values only.

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status
- Here we convert the user to a defaulter or a non-defaulter on the base of the loan-status.
- Finally we assign 0 to defaulter and 1 to the latter.

In [281]:
strings_header

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [282]:
strings_loan_data[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [283]:
print(np.unique(strings_loan_data[:,1]).size)
np.unique(strings_loan_data[:,1])

9


array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [284]:
# Here we assign the loan status as good or bad, on basis of will the loan be repaid or not.
good_status = ['Current','Fully Paid','Issued','In Grace Period','Late (16-30 days)']
bad_status = ['Charged Off','Default','Late (31-120 days)','']

In [285]:
strings_loan_data[:,1] = np.where(np.isin(strings_loan_data[:,1],good_status),1,0)
np.unique(strings_loan_data[:,1])

array(['0', '1'], dtype='<U69')

### Term
- Here we see the time in which the loan is paid by the client.
- If its 60 months, then its a defaulter, while 36 months is taken to be a good value.

In [286]:
strings_header

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [287]:
np.unique(strings_loan_data[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [288]:
strings_loan_data[:,2] = np.chararray.strip(strings_loan_data[:,2]," months")
strings_loan_data[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [289]:
np.unique(strings_loan_data[:,2])

array(['', '36', '60'], dtype='<U69')

In [290]:
strings_header[2]='term_months' #To make more sense of the the unit of data.

In [291]:
# We are changing the missing values to 60 to consider the worst case scenario.
# We are not converting this to a binary dummy variable as we did for loan_status as nothing is given in instructions, 
# in real life, however we do consult with team about the significance of the variables.
strings_loan_data[:,2] = np.where(strings_loan_data[:,2]=='',
                                  '60',
                                  strings_loan_data[:,2])
np.unique(strings_loan_data[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade
- Here we operate on columns and see which are redundant ones.
- However before removing redundant columns we make use of it to fill any missing values if possible and then remove it fully.
- We finally assign numeric values to the strings as per the instructions.

In [292]:
strings_header 

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [293]:
np.unique(strings_loan_data[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [294]:
np.unique(strings_loan_data[:,4]) 
#Since we have subgrade column and the grades can be derived from sub-grade, grades column is redundant here.

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [295]:
# But before removing grade, we will fill the subgrades missing values.
# If for a row, there is no value for subgrade and there is a grade so we assign the string of grade+5 to it, where 
# the grade is taken from the grade column.

#### Filling Sub Grade

In [296]:
for i in np.unique(strings_loan_data[:,3])[1:]:
    strings_loan_data[:,4] = np.where((strings_loan_data[:,4] == '') & (strings_loan_data[:,3] == i),
                                      i + '5',
                                      strings_loan_data[:,4])

In [297]:
np.unique(strings_loan_data[:,4],return_counts = True) # So after substitution we stil have 9 empty rows.
# Now these rows don't have grade and neither the subgrade.

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [298]:
# We will assign such empty values as another subgrade i.e. H5
strings_loan_data[:,4] = np.where(strings_loan_data[:,4]=='','H5',strings_loan_data[:,4])

In [299]:
np.unique(strings_loan_data[:,4],return_counts = True) #Now we don't have any missing values in the subgrade.
# After this we will remove the grade column.

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

#### Removing Grade

In [300]:
strings_loan_data = np.delete(strings_loan_data,3,axis = 1)

In [301]:
strings_header = np.delete(strings_header,3)

In [302]:
np.unique(strings_loan_data[:,3]) # We get the sub grades column only.

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69')

#### Converting Sub Grade
- Here we assign numeric strings to subgrades.

In [303]:
keys = list(np.unique(strings_loan_data[:,3]))                         
values = list(range(1, np.unique(strings_loan_data[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [304]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H5': 36}

In [305]:
for i in np.unique(strings_loan_data[:,3]):
        strings_loan_data[:,3] = np.where(strings_loan_data[:,3] == i, 
                                          dict_sub_grade[i],
                                          strings_loan_data[:,3])

In [306]:
np.unique(strings_loan_data[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status
- Verification status needs to be processed similarly as the loan_status and we need to categorize it into defaulters and non-defaulters.
- We will assign 1 to those who have a financial backing and 0 to those who don't.

In [307]:
strings_header 

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [308]:
np.unique(strings_loan_data[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [309]:
# We will assign Not Verified, '' values to be 0, and rest as 1 in string format.
strings_loan_data[:,4] = np.where(((strings_loan_data[:,4] == 'Not Verified')|(strings_loan_data[:,4] == '')),0,1)

In [310]:
np.unique(strings_loan_data[:,4])

array(['0', '1'], dtype='<U69')

### URL
- In URL we actually strip the values to keep only the important part in URL which is unique to each entry.
- Further on analysis if we find that URL is identical to ID we remove URL.

In [311]:
strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [312]:
np.unique(strings_loan_data[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [313]:
strings_loan_data[:,5] = np.chararray.strip(strings_loan_data[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [314]:
strings_loan_data[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [315]:
#Since this data is similar to id, just in string format we will remove this url column.
#But before that lets check are all the values same.
np.array_equal(strings_loan_data[:,5].astype(np.int32),numeric_loan_data[:,0].astype(np.int32))

True

In [316]:
#We remove the Urls column from the string headers and the data array.
#strings_header = np.delete(strings_header,5)
strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [317]:
strings_loan_data = np.delete(strings_loan_data,5,axis = 1)
strings_loan_data[:,5] # We don't get urls as output.

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [318]:
strings_header = np.delete(strings_header,5)

In [319]:
strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

### State Address
- Here we change the address to a more grouped one, i.e. according to regions and then number the regions.
- The state addresses are made on a baseline, here the baseline is the state IOWA.


In [320]:
strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [321]:
strings_header[5] = 'state_address'

In [322]:
np.unique(strings_loan_data[:,5]).size

50

In [323]:
state_names,state_count = np.unique(strings_loan_data[:,5],return_counts = True)
#We want to see the results in descending order to see which state has generally more accounts in the bank.

states_count_sorted = np.argsort(-state_count) # This will give indices for max to min values 
# of state count in descending order.
state_names[states_count_sorted],state_count[states_count_sorted]

# With this we are able to observe that more states have missing values.
# So we have too little data for too many variables so we will generalize the data as per regions and we will 
# assign 0 to the missing values, so that they are not able to influence the data set.

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [324]:
strings_loan_data[:,5]= np.where(strings_loan_data[:,5]=='',
                                 0,
                                 strings_loan_data[:,5])
strings_loan_data[:,5]
# After this we assign region to the states and then numeric strings to the regions.

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [325]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [326]:
strings_loan_data[:,5] = np.where(np.isin(strings_loan_data[:,5],states_west),1,strings_loan_data[:,5])
strings_loan_data[:,5] = np.where(np.isin(strings_loan_data[:,5],states_south),2,strings_loan_data[:,5])
strings_loan_data[:,5] = np.where(np.isin(strings_loan_data[:,5],states_midwest),3,strings_loan_data[:,5])
strings_loan_data[:,5] = np.where(np.isin(strings_loan_data[:,5],states_east),4,strings_loan_data[:,5])

In [327]:
np.unique(strings_loan_data[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers
- Finally after converting each string data to a general numeric value we need to convert it to numeric value.
- On a brief, we have converted the following:
    + Issue_date to simple Months with numeric values.
    + Loan_Status to simple 0 and 1.
    + Term_Months to simple 0 and 1.
    + Sub_grade to values in 1 to 36.
    + Verification_status to 0 and 1.
    + State_address to 1 to 4.
- Further now we will convert the strings to numbers.
  

In [328]:
strings_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [329]:
strings_loan_data

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [330]:
strings_loan_data = strings_loan_data.astype(dtype = int)

In [331]:
strings_loan_data

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings
- Once we are done with preprocessing the strings part we will create a checkpoint and store the strings data separately in a nypz file with its headers.

In [332]:
checkpoint_strings = checkpoint('checkpoint_strings',strings_header,strings_loan_data)

In [333]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [334]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [335]:
np.array_equal(strings_loan_data,checkpoint_strings['data'])

True

## Manipulating Numeric Columns
- Now we have all the columns in the numeric form, however we need to modify the numeric columns a bit which are completely numeric i.e. they were the original numbers at the start.
- We will replace the filler_values assigned to NaNs with the min for certain columns and the max for the rest columns while with mean for the rest.

In [336]:
numeric_header
# Here we want to assign the worst_case values so we assign max to all the columns accept the funded amount.
# With the funded amount being least its the worst_case, while assigning max to rest is the worst_case.

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [337]:
np.isnan(numeric_loan_data).sum() # The sum is 0 because we replaced the filler values with the max of the whole array.
# Thus we now need to substitute the filler values with min and max values for the specific values.

0

In [338]:
numeric_loan_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [339]:
temporary_fill

68616520.0

### Substitute "Filler" Values

In [340]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [341]:
# We just check is there any temporary_fill in the ID.

In [342]:
np.isin(numeric_loan_data[:,0],temporary_fill).sum() #Returns true to those position where temporary_fill is present.
# Since output is 0 there are no missing values in ID.

0

#### Temporary Stats

In [343]:
temporary_stats #Here first row is for min, second is for mean and 3rd is for max.
# We see nan values cause temporary_stats was formed with raw_dataset. 
# So we will use the column numeric which has the column numbers for numeric data in the raw dataset itself.
# Being for raw data the column numeric works perfectly.
temporary_stats[:,numeric_columns]

#Now we need to assign element [0,2] to missing values in funded_amt column and rest from 3rd row to remaining columns
# except id.

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount
- Assigning the min from the temporary_stats to the numeric_loan_data 3rd column.

In [344]:
numeric_header,numeric_columns # We will use numeric_column[2] for funded amount.

(array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19'),
 array([ 0,  2,  4,  6,  7, 13], dtype=int64))

In [345]:
numeric_loan_data[:,2] = np.where(numeric_loan_data[:,2] == temporary_fill, 
                                  temporary_stats[0, numeric_columns[2]],
                                  numeric_loan_data[:,2])
numeric_loan_data[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [346]:
np.isin(numeric_loan_data[:,2],temporary_fill).sum() # So no temporary fill hence further.

0

#### Loaned Amount, Interest Rate, Total Payment, Installment
- Assigning the max from the temporary_stats to the numeric_loan_datas numeric columns.

In [347]:
for i in [1,3,4,5]:
    numeric_loan_data[:,i] = np.where(numeric_loan_data[:,i]==temporary_fill,
                                      temporary_stats[2,numeric_columns[i]],
                                      numeric_loan_data[:,i])

In [348]:
numeric_loan_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [349]:
np.isin(numeric_loan_data,temporary_fill).sum() # Thus we have removed the temporaryfill values from the whole numeric array.

0

### Currency Change
- Here we convert the USD to EUR, however to keep dataset a bit consistent we have both the currencies in the dataset and we keep altering the headers too as we have been doing along the way.

#### The Exchange Rate

In [350]:
EUR_USD = np.genfromtxt('./Data/EUR-USD.csv',delimiter = ',',autostrip = 1,dtype = str)
EUR_USD
# We only need the closing conversion rates for each entry, thus we only will keep close columns.
EUR_USD = np.genfromtxt('./Data/EUR-USD.csv',delimiter = ',',autostrip = 1,usecols = 3,skip_header = 1)
EUR_USD.shape # We have exchange rates for every month.
# This will help to put exchange rates as per issue_dates month numbers.

(12,)

In [351]:
strings_loan_data,strings_header

(array([[ 5,  1, 36, 13,  1,  1],
        [ 0,  1, 36,  5,  1,  4],
        [ 9,  1, 36, 10,  1,  4],
        ...,
        [ 6,  1, 36,  5,  1,  1],
        [ 4,  1, 36, 17,  1,  3],
        [12,  1, 36,  4,  0,  3]]),
 array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
        'state_address'], dtype='<U19'))

In [352]:
exchange_rate = strings_loan_data[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)    

# Since we have months from 1 to 12 itself, there are missing values assigned as value 0 in the issue date, thus 
# we assign, missing values with the mean exchange rate.
exchange_rate = np.where(exchange_rate == 0,
                        np.mean(EUR_USD),
                        exchange_rate)
exchange_rate,exchange_rate.shape
#Now we need to put this exchnage rate as a new column.

(array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09]), (10000,))

In [353]:
exchange_rate = np.reshape(exchange_rate,(10000,1)) #This will make the array 2D and thus able to hstack with the strings_loan_data

In [354]:
numeric_loan_data = np.hstack((numeric_loan_data,exchange_rate))

In [355]:
# Addding exchange rate to column name.
numeric_header = np.concatenate((numeric_header,np.array(['exchange_rate'])))

In [356]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR
- Here we want to convert the USD amounts stored in loan_amnt, funded_amnt, installment, total_pymnt to Euros.
- We know how much 1 euros means in dollars by exchange rate, so we will divide the amounts by the exchange rates itself.
- We will create new columns with Euro values and further stack them in our numeric_dataset.

In [357]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [358]:
columns_dollar = [1,2,4,5]
numeric_loan_data[:,columns_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [359]:
# With this code we actually divide every dollar columns with the exchange rate and store 
# each columns individually in the original array.
for i in columns_dollar:
    numeric_loan_data = np.hstack((numeric_loan_data, np.reshape(numeric_loan_data[:,i] / numeric_loan_data[:,6], (10000,1))))

In [360]:
numeric_loan_data,numeric_loan_data.shape # First we had only 7 columns now we added 4 more so we have 11 now.

(array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
        [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
        [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
        ...,
        [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
        [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
        [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]]),
 (10000, 11))

#### Expanding the header

In [361]:
header_additional = np.array([column_name + '_EUR' for column_name in numeric_header[columns_dollar]])

In [362]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [363]:
numeric_header = np.concatenate((numeric_header,header_additional))

In [364]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [365]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [366]:
numeric_header = numeric_header[columns_index_order]

In [367]:
numeric_header

array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
       'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [368]:
numeric_loan_data = numeric_loan_data[:,columns_index_order]

In [369]:
numeric_loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest Rate
- We are just getting its values in the range of 0 and 1

In [370]:
numeric_header

array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
       'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [371]:
numeric_loan_data[:,5] #These are the interest rates and they are required in 0 to 1.

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [372]:
numeric_loan_data[:,5] = numeric_loan_data[:,5]/100

In [373]:
numeric_loan_data[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [374]:
checkpoint_numeric = checkpoint('checkpoint-numeric',numeric_header,numeric_loan_data)

In [375]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
        'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [376]:
np.array_equal(checkpoint_numeric['data'],numeric_loan_data)

True

## Creating the "Complete" Dataset
- Finally we will be creating a single dataset from the numeric and string arrays which we have found out above.
- We are using the checkpoints so even if the data is changed its intact in our checkpoints.

In [377]:
checkpoint_strings['header'],checkpoint_numeric['header']

(array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
        'state_address'], dtype='<U19'),
 array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
        'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'))

In [378]:
checkpoint_strings['data'].shape,checkpoint_numeric['data'].shape

((10000, 6), (10000, 11))

In [379]:
# Since the no. of rows in the dataset are equal we will stack them side by side.
# We are keeping the string data first.
loan_data = np.hstack((checkpoint_strings['data'],checkpoint_numeric['data']))
loan_data

array([[   5.  ,    1.  ,   36.  , ..., 9452.96, 8624.69,    1.1 ],
       [   0.  ,    1.  ,   36.  , ..., 4679.7 , 4232.39,    1.11],
       [   9.  ,    1.  ,   36.  , ..., 1969.83, 1750.04,    1.13],
       ...,
       [   6.  ,    1.  ,   36.  , ..., 2185.64, 1947.47,    1.12],
       [   4.  ,    1.  ,   36.  , ..., 3199.4 , 2878.63,    1.11],
       [  12.  ,    1.  ,   36.  , ...,  301.9 ,  276.11,    1.09]])

In [380]:
# Checking are there any null values in the final dataset.
np.isnan(loan_data).sum()

0

In [381]:
# Combining the headers too.
header_full = np.hstack((strings_header, numeric_header))

In [382]:
header_full[0],header_full[6] = header_full[6],header_full[0] # Bringing the id to the start.

In [383]:
loan_data[:,0],loan_data[:,6] = loan_data[:,6],loan_data[:,0] #Bringing ids to the start in the dataset.

In [384]:
loan_data,header_full

(array([[48010226.  ,        1.  ,       36.  , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,        1.  ,       36.  , ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,        1.  ,       36.  , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,        1.  ,       36.  , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,        1.  ,       36.  , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,        1.  ,       36.  , ...,      301.9 ,      276.11,        1.09]]),
 array(['id', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address',
        'issue_date', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
        'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'))

## Sorting the New Dataset
- We will sort the data as per the id.
- However with argsort as we get the index where each element needs to belong to we will apply it to each column, so this will sort whole array by id's thus keeping the data for every row intact.

In [385]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [386]:
loan_data

array([[  373332.  ,        1.  ,       36.  , ...,     1072.82,      974.5 ,        1.1 ],
       [  575239.  ,        1.  ,       60.  , ...,      959.75,      871.79,        1.1 ],
       [  707689.  ,        1.  ,       36.  , ...,     3726.25,     3325.42,        1.12],
       ...,
       [68614880.  ,        1.  ,       36.  , ...,        0.  ,        0.  ,        1.09],
       [68615915.  ,        1.  ,       36.  , ...,        0.  ,        0.  ,        1.09],
       [68616519.  ,        1.  ,       36.  , ...,        0.  ,        0.  ,        1.09]])

In [387]:
# Validating whether the data is sorted or not.
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

## Storing the New Dataset
- Finally after sorting as per the id's we will attach the headers with v stack and save the data in a text file.
- We can view it after saving.

In [388]:
loan_data = np.vstack((header_full,loan_data))

In [389]:
loan_data #The data came in strings because vstack converts it to the datatype 
# that can store the data and also with least space. Here thus we have dtype = unicode in 32 bits.

array([['id', 'loan_status', 'term_months', ..., 'total_pymnt', 'total_pymnt_EUR',
        'exchange_rate'],
       ['373332.0', '1.0', '36.0', ..., '1072.82', '974.4960808923015', '1.100897192955017'],
       ['575239.0', '1.0', '60.0', ..., '959.75', '871.788942820218', '1.100897192955017'],
       ...,
       ['68614880.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246'],
       ['68615915.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246'],
       ['68616519.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246']], dtype='<U32')

In [390]:
np.savetxt('loan_data_preprocessed_by_me.csv',
           loan_data,
           fmt = '%s',
           delimiter = ',')

In [391]:
# Validating that everything is great.
loan_data_check = np.loadtxt('loan_data_preprocessed_by_me.csv',delimiter = ',',dtype = str)
loan_data_check

array([['id', 'loan_status', 'term_months', ..., 'total_pymnt', 'total_pymnt_EUR',
        'exchange_rate'],
       ['373332.0', '1.0', '36.0', ..., '1072.82', '974.4960808923015', '1.100897192955017'],
       ['575239.0', '1.0', '60.0', ..., '959.75', '871.788942820218', '1.100897192955017'],
       ...,
       ['68614880.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246'],
       ['68615915.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246'],
       ['68616519.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246']], dtype='<U19')

In [392]:
np.array_equal(loan_data,loan_data_check)

True

In [393]:
# Finally the data is fully preprocessed, doesn't have any null values, and dataset is ready to be used in the model.
# Good luck Analytics team with the further analysis.